### =================================================================
### A LIRE AVANT UTILISATION
### =================================================================
### Pour utiliser ce fichier de test de l'api, il faut avant tout
### installer l'extension vscode 'REST client'.
### Ensuite, il faudra ajouter la variable 'CLERK_TEST_TOKEN' dans le
### fichier '.env' à la racine du projet. Vous pouvez vous baser sur
### le fichier '.env.example'. Il faudra pour finir se connecter sur
### Doppler (via ce lien https://dashboard.doppler.com/workplace/594510d31ae1dcfd7568/projects/owl-api/configs/dev)
### avec le compte 'team.owl.project@proton.me' avec son mdp.
### =================================================================
### Variables d'environnement
### Changez ces valeurs selon vos besoins
### =================================================================
@baseUrl = http://localhost:8080
@authToken = {{$dotenv CLERK_TEST_TOKEN}}


### =================================================================
### Endpoints Publics (pas besoin d'authentification)
### =================================================================

# @name TestRacine
# Teste si l'API est en ligne
GET {{baseUrl}}/

###

# @name TestConnexionDB
# Teste si la connexion à la base de données fonctionne
GET {{baseUrl}}/api/test/db


### =================================================================
### Endpoints Protégés (nécessite un token d'authentification)
### =================================================================

# @name GetTousLesCapteurs
# Récupère tous les capteurs pour l'utilisateur authentifié
GET {{baseUrl}}/api/sensors
Authorization: Bearer {{authToken}}

###

# @name GetCapteursFenetre
# Récupère uniquement les capteurs de type "fenêtre"
GET {{baseUrl}}/api/sensors/windows
Authorization: Bearer {{authToken}}

###

@sensorId = 078c04be-6c1c-4950-a429-f95ab2971003

# @name GetLectures24h
# Récupère les lectures des dernières 24 heures pour un capteur spécifique
GET {{baseUrl}}/api/sensors/{{sensorId}}/readings?period=24h
Authorization: Bearer {{authToken}}

###

# @name GetLectures7j
# Récupère les lectures des 7 derniers jours pour un capteur spécifique
GET {{baseUrl}}/api/sensors/{{sensorId}}/readings?period=7d
Authorization: Bearer {{authToken}}