### =================================================================
### A LIRE AVANT UTILISATION
### =================================================================
### Pour utiliser ce fichier de test de l'api, il faut avant tout
### installer l'extension vscode 'REST client'.
### Ensuite, il faudra ajouter la variable 'CLERK_TEST_TOKEN' dans le
### fichier '.env' à la racine du projet. Vous pouvez vous baser sur
### le fichier '.env.example'. Il faudra pour finir se connecter sur
### Doppler (via ce lien https://dashboard.doppler.com/workplace/594510d31ae1dcfd7568/projects/owl-api/configs/dev)
### avec le compte 'team.owl.project@proton.me' avec son mdp.
### =================================================================
### Variables d'environnement
### Changez ces valeurs selon vos besoins
### =================================================================
@baseUrl = http://localhost:8080
@authToken = {{$dotenv CLERK_TEST_TOKEN}}


### =================================================================
### Endpoints Publics (pas besoin d'authentification)
### =================================================================

# @name TestRacine
# Teste si l'API est en ligne
GET {{baseUrl}}/api/

###

# @name TestConnexionDB
# Teste si la connexion à la base de données fonctionne
GET {{baseUrl}}/api/test/db


### =================================================================
### Endpoints Protégés (nécessite un token d'authentification)
### =================================================================

# @name GetTousLesCapteurs
# Récupère tous les capteurs pour l'utilisateur authentifié
GET {{baseUrl}}/api/sensors
Authorization: Bearer {{authToken}}

###

# @name GetCapteursFenetre
# Récupère uniquement les capteurs de type "fenêtre"
GET {{baseUrl}}/api/sensors/windows
Authorization: Bearer {{authToken}}

###

@windowId = 2a1a1132-98a7-4a32-8cd5-9a5a6aed7ee3
@temperatureId = 2396c034-eb47-4b0d-a8b9-4490991f9040

@targetDate = 2025-11-20T11:07:00.000Z

# @name GetLectures24h
# Récupère les lectures des dernières 24 heures pour un capteur spécifique
GET {{baseUrl}}/api/sensors/{{temperatureId}}/readings?period=24h&refDate={{targetDate}}
Authorization: Bearer {{authToken}}

###

# @name GetLectures7j
# Récupère les lectures des 7 derniers jours pour un capteur spécifique
GET {{baseUrl}}/api/sensors/{{windowId}}/readings?period=7d&refDate={{targetDate}}
Authorization: Bearer {{authToken}}

###

# @name GetCapteursFenetreHistorique
# Récupère uniquement les capteurs de type "fenêtre"
GET {{baseUrl}}/api/sensors/windows/history?date={{targetDate}}
Authorization: Bearer {{authToken}}

###
# @name GetStatsHoraires
# Récupère la distribution des ouvertures par heure
GET {{baseUrl}}/api/sensors/windows/stats?refDate={{targetDate}}
Authorization: Bearer {{authToken}}




### Test nouveau endpoint température groupé
GET {{baseUrl}}/api/temperature/hubs/TON_HUB_ID_ICI/readings
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zNDVyYTNtWUREektYNXFrTE9EQ0xKRUhjbUwiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3NjU4OTYxMzYsImZ2YSI6WzE0NjEsLTFdLCJpYXQiOjE3NjU4OTYwNzYsImlzcyI6Imh0dHBzOi8vc3RpcnJpbmctaHllbmEtODkuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzY1ODk2MDY2LCJzaWQiOiJzZXNzXzM2c3cxbHAyWkl0UHVsWnQ1QmpteW1ITk5aWCIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzZZYnRTSG1KemI5VHViZ1JQT3R6MjlRYnRUIiwidiI6Mn0.q_28QAp2GWUy3IUFr4Z5XTKp004zQgP-rUAeS4X-xIF_V3wf3OAXD83HDNebz_TVs1dFoOa7fZR4qqJ5XUy86ge_td9UGF9z12Um-07bqdLjG7kgZuZxRYdumzK-LDWkP68cyXnbizUoMS64DqQct0VILqW6nrYMfu-b_ZOtUOMOddo3Yloj1n3aEk-y74hfPn8DwhQ74EXoeaG036YAkYNuWfCPos5QMwyRdPkjMZTCj6ZTwV1KTbC1Xh__AqOXKRJ0onRNT0jWus7LviPriGiYNCYcE7Hb4uCtYgfrHU3TvdI_LpO6i54qysOQx4Z3FJsiqy0MRtYHrGWA6LYfBg
